# Generated by Django 2.2 on 2019-10-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='账号')),
                ('name', models.CharField(max_length=16, verbose_name='真实姓名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('sex', models.IntegerField(default=1, verbose_name='性别（1-男 2-女）')),
                ('address', models.CharField(max_length=255, verbose_name='收货地址')),
                ('code', models.CharField(max_length=6, verbose_name='邮政编码')),
                ('phone', models.CharField(max_length=16, verbose_name='电话号码')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱地址')),
                ('state', models.IntegerField(default=1, verbose_name='会员状态（1-启用 2-禁用 3-后台管理员）')),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('modifytime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '会员信息',
                'verbose_name_plural': '会员信息',
            },
        ),
    ]
